name: Volumetric_ART
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - scipy
  - pip

  - pip:
    - pickle5
    - scikit-optimize

    
    
